CF-661 Invalid glance image URL breaks VM migration
Some images may raise CommunicationError during download:

```
CommunicationError: Error finding address for
https://some.openstack.deployment.com/v1/images/4c5d0874-933d-4eef-859e-697d44d51bd1
```

This exception was not handled properly and resulted in VM migration
failures. This patch resolves the issue by correclty handling this
exception.